name: Stark Web Audit

on:
  workflow_dispatch:
    inputs:
      token:
        description: 'Stark Token'
        required: true

jobs:
  accessibility-audit:
    runs-on: ubuntu-latest

    name: Accessibility Audit
    steps:
      - name: Checkout code
        id: code-checkout
        uses: actions/checkout@v3

      - name: Audit
        id: stark
        uses: stark-contrast/accessibility-check-action@0.2.0-beta.0
        with:
            # Most of the following values are simply shell commands. You can use these to set up the container as needed for your app
            token: ${{ github.event.inputs.token }} # The action will use this to send an audit report back to Stark.
            setup: 'npm i' # [Optional] Set up the container. Install some tools, export variables, etc.
            build: 'npm run build' # [Optional] Build steps. Use && for multiple steps.
            serve: 'npm run preview -- --port 4173' # [Optional] Tell us how to serve your app.
            wait_time: 5000 # [Required, default 5000] Milliseconds to wait before your app can start serving
            url: 'http://127.0.0.1:4173/' # [Required] Where does your app run? e.g. http://localhost:3000.
            cleanup: '' # [Optional] After scanning, the command running in serve step is auto terminated. Use this to run any cleanup commands.